baseurl = "/"
UglyURLs = true
languageCode = "en"
title = "Sample Site"
copyright = ""
paginate = 3

theme = "minimage"

[params]
  description = "This is a sample site."
  logo = '/image/logo.png'

[taxonomies]

